--<ScriptOptions statementTerminator=";"/>

ALTER TABLE EDI_ANBINDUNG DROP INDEX ANR;

ALTER TABLE EDI_ANBINDUNG DROP INDEX FK_EDI_ANBINDUNG_EDI_KONTEXT_ID;

ALTER TABLE EDI_ANBINDUNG DROP INDEX ANBINDUNG;

DROP TABLE EDI_ANBINDUNG;

